FROM ubuntu:20.04
CMD ["apt","-y","install","docker-compose"]
COPY ./src/ /var/cdp
COPY ./docker-compose.yml /var/cdp
CMD ["cd","/var/cdp/src/back"]
CMD ["mvn","package","-DskipTests"]
CMD ["cd","/var/cdp/src/front"]
CMD ["ng","build"]
CMD ["cd","/var/cdp"]
CMD ["docker-compose","up"]
EXPOSE 8080