FROM maven:latest as maven
WORKDIR /usr/src/app

COPY . .
RUN mvn package -Dmaven.test.skip=true 


FROM tomcat:latest
COPY --from=maven /usr/src/app/target/back-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]