FROM node:15.3.0-alpine3.10 as node
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
RUN npm i -g @angular/cli
COPY . .
RUN ng build --prod


FROM nginx:latest
COPY --from=node /usr/src/app/dist/front /usr/share/nginx/html
COPY ./docker_conf/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80